### ISSUE TITLE
本地部署的ai绘图出了问题

### ISSUE THREAD

**Issue by jianliu123** [x-dr/wechaty-bot#3]
![2`PSWK80TV$J BA8KFI} ~I](https://user-images.githubusercontent.com/100300754/211143280-f2c0e846-bf4f-4fec-8d86-97c288459842.png)

**Comment by x-dr** [comment]
> ![2`PSWK80TV$J BA8KFI} ~I](https://user-images.githubusercontent.com/100300754/211143280-f2c0e846-bf4f-4fec-8d86-97c288459842.png)
> 
> 

建议用docker运行
