### ISSUE TITLE
图片上传失败，超过1M的媒体文件

### ISSUE THREAD

**Issue by GTreeSoftware** [x-dr/wechaty-bot#4]
cause: Error: read ECONNRESET
      at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20) {
    errno: -104,
    code: 'ECONNRESET',
    syscall: 'read'
  },
  tips: '上传媒体文件失败'

**Comment by x-dr** [comment]
如果是AI绘画发送图片失败，那修改这就行了
[get-ai-image.js#L16](https://github.com/x-dr/wechaty-bot/blob/43aea1c8db1218d6d1040cd2e59e9d0b61a30aa2/utils/get-ai-image.js#L16)
